url: "https://devleoko.github.io/FirstContact"
primaryColor: "#fa4a53"
title: "Max Mustermann - Human"
logo: "logo.svg"
legalNotice: "Impressum"
# formspree.io works great for static sites
contactAction: ""
